show_analysis_paths: False
show_analysis_time: False

custom_data:
  mapq_quality:
    file_format: 'tsv'
    section_name: 'Mapping Quality Distribution'
    description: "This plot shows the number of genomic positions for each mapping quality value. Mapping quality reflects the confidence of read alignment, typically ranging from 0 to 60."
    plot_type: 'linegraph'
    pconfig:
      title: ""
      id: 'mapq_lineplot'
      xlab: 'Mapping Quality'
      ylab: 'Number of Genomic Positions'

  insert_size:
    file_format: 'tsv'
    section_name: 'Insert Size Distribution'
    description: "This histogram displays the distribution of insert sizes (distance between paired-end reads). A typical insert size distribution should show a smooth peak."
    plot_type: 'linegraph'
    pconfig:
      title: ""
      id: 'insert_lineplot'
      xlab: 'Insert Size (bp)'
      ylab: 'Number of Read Pairs'

  clipping:
    file_format: 'tsv'
    section_name: 'Mapped Reads Clipping Profile'
    description: "Shows the percentage of clipped bases at each read position. Clipping (hard or soft) is inferred from the CIGAR string in the BAM file and may indicate sequencing or alignment artifacts."
    plot_type: 'linegraph'
    pconfig:
      title: ""
      id: 'clipping_lineplot'
      xlab: 'Read Position (bp)'
      ylab: 'Percentage of Clipped Bases'

  nucleotide_content:
    file_format: 'tsv'
    section_name: 'Mapped Reads Nucleotide Content'
    description: "Displays the proportion of each nucleotide (A, C, G, T) at each read position. Unbalanced content could indicate biases in sequencing or library preparation."
    plot_type: 'linegraph'
    pconfig:
      title: ""
      id: 'nucleotide_content_lineplot'
      xlab: 'Read Position (bp)'
      ylab: 'Nucleotide Frequency (%)'

  indels:
    file_format: 'tsv'
    section_name: 'Homopolymer Indels Distribution'
    description: "This bar plot shows the number of insertions or deletions (indels) found within homopolymer regions (e.g., stretches of AAAAA) and non-homopolymer regions. High numbers may suggest sequencing issues."
    plot_type: 'bargraph'
    pconfig:
      title: ""
      id: 'indels_lineplot'
      xlab: 'Indel Context'
      ylab: 'Number of Indels'
      cpswitch: false #Elimina la opcion de mostrar porcentajes al no calcularla bien


  fraction:
    file_format: 'tsv'
    section_name: 'Genome Fraction Coverage'
    description: "Shows the percentage of the reference genome covered at or above different coverage thresholds. For example, 80% at 25X means 80% of the genome is covered by at least 25 reads."
    plot_type: 'linegraph'
    pconfig:
      title: ""
      id: 'fraction_lineplot'
      xlab: 'Coverage Threshold (X)'
      ylab: 'Reference Covered (%)'

sp:
  mapq_quality:
    fn: 'mapping_quality_plot_mqc.txt'
  insert_size:
    fn: 'insert_size_plot_mqc.txt'
  clipping:
    fn: 'mapped_reads_clipping_profile_mqc.txt'
  nucleotide_content:
    fn: 'mapped_reads_nucleotide_content_mqc.txt'
  indels:
    fn: 'homopolymer_indels_mqc.txt'
  fraction:
    fn: 'genome_fraction_coverage_mqc.txt'


